### ISSUE TITLE
GetProducts "Amazon Api didn't respond with Okay, see exception for more details"

### ISSUE THREAD

**Issue by mjw2022** [abuzuhri/Amazon-SP-API-CSharp#309] opened 2022-09-05 06:43 UTC
Hi, thanks for adding MerchantShippingGroup field to the GetProducts()
After upgrading to ver 1.4.25 I get an error with GetProducts

"Amazon Api didn't respond with Okay, see exception for more details"

"Enumeration yielded no results"

If I revert back to  1.4.23 it works OK.

Thanks

Mark

**Comment by gambit823** [comment] 2022-09-06 19:48
I am having the same issue with Orders.GetOrderItems. I've tracked it down to the fix for issue #287. That fix added the following line to Source/FikaAmazonAPI/Services/RequestService.cs:
RequestClient.ThrowOnAnyError = true;

If you remove that line everything works again.

**Comment by gambit823** [comment] 2022-09-06 19:58
FYI this is a duplicate of #308.

**Closed** 2022-09-06 21:23 UTC

**Comment by abuzuhri** [comment] 2022-09-06 21:24
Please check v1.4.26

**Comment by mjw2022** [comment] 2022-09-07 14:33
v1.4.26 works well for me. Thanks
