### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException: The given key 'UNSET' was not present in the dictionary.

### ISSUE THREAD

**Issue by wkf0660** [abuzuhri/Amazon-SP-API-CSharp#172] opened 2022-04-29 04:32 UTC
Dear friend,
Do you know what's  error for it . may be is eh 
var list = await amazonConnection.Orders.GetOrdersAsync(serachOrderList);

System.Collections.Generic.KeyNotFoundException: The given key 'UNSET' was not present in the dictionary.

![image](https://user-images.githubusercontent.com/41567931/165885547-4f1a80a0-46f0-4f5d-b2cb-168610925ddb.png)

**Comment by wkf0660** [comment] 2022-04-29 04:33
may be is call limit

**Comment by abuzuhri** [comment] 2022-04-29 06:51
Can you give us sample code you are used when you get this error

**Comment by nafberger** [comment] 2022-05-04 17:06
Hi @abuzuhri the root issue is getting over the limit, I asked in another issue 2 things, first throw back an exception to the caller to be able to intelligently handle amazon throttling and also send back the raw header, i.e. the throttling info amazon sends back in every call , so the caller should be able to make intelligent decisions himself about the throttling .

can it please be done, we are ready to pay. but please respond.

**Comment by abuzuhri** [comment] 2022-05-04 17:12
I will take look tonight, really supper busy this month.

Please share sample code and I will try my best this week to do it

**Comment by nafberger** [comment] 2022-05-04 17:30
@abuzuhri  but this, if u can do fast to nuget, I will really appreciate

https://github.com/abuzuhri/Amazon-SP-API-CSharp/issues/169

**Comment by abuzuhri** [comment] 2022-05-04 17:32
Ok give all details with sample code and I will try my best fix today

**Comment by abuzuhri** [comment] 2022-05-05 22:23
> UNSET

Its look like error in parsing JSON 

Please share stack trace for this error will help also to fix it

**Comment by abuzuhri** [comment] 2022-05-05 22:32
@nafberger if you share the error ASAP i will try to fix in the same day

**Comment by nafberger** [comment] 2022-05-05 23:14
@abuzuhri honestly I didn't encounter the problem lately but I will check the logs, but I thought the the problem is a result of throttling , since you say that it is a json parse error i will try to reproduce the problem

**Comment by abuzuhri** [comment] 2022-05-07 11:34
I will closed this since it’s look like JSON parsing error

**Closed by abuzuhri** 2022-05-07 11:34 UTC
